version: "3.9"
services:

  qdrant-db:
    image: qdrant/qdrant:master
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data:/qdrant/storage

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./data:/app/data